### ISSUE TITLE
org.wso2.carbon.apimgt.gataway & org.wso2.carbon.apimgt.impl

### ISSUE THREAD

**Issue by giuffresoft79** [wso2/carbon-apimgt#2874]
I see that  there is a potential circular dependency between the specified modules.
In fact, you refer to a stub module for example:

 stub = new APIAuthenticationServiceStub(ServiceReferenceHolder.getContextService().getClientConfigContext(),
                                            getServiceEndpointToClearCache(environment, "APIAuthenticationService"))

How to load the correct module during execution?

**Comment by harsha89** [comment]
@giuffresoft79 were you encounter any issue?

**Comment by giuffresoft79** [comment]
I wanted just to understand if indeed the APIAuthenticationAdminClient class is used in production with reference to the stub module of gateway or not. But it seems strange.

The class should refer to APIAuthenticationService in org.wso2.carbon.apimgt.gateway module.

I'm missing something in your architecture?

**Comment by giuffresoft79** [comment]
I understand that the implementation is present in these stub modules that in the sources are not distributed. Right? I decompiled one of these jar

**Comment by jaadds** [comment]
Hi Roger,
Let me briefly explain how Services are used in this repo, so that that your concern about circular dependancy will be addressed.

When writing a service we normally follow a code-first approach. 
Suppose we need to add a new operation to APIAuthenticationService. So first we'd change the service implementation adding the necessary code. Then we'd obtain the WSDL for the modified service (at the development time, usually this is done by patching the product with the modified jar and starting up the product, but theoretically, you should be able to get this WSDL by dropping the jar in an axis2 container). Once you start the product, you can download the WSDL by accessing service's URL which in this case is https://localhost:9443/services/APIAuthenticationAdminService?wsdl.

Using this WSDL, we'd generate the stubs needed to call that service. It's those WSDL's and the commands to generate the stubs that are located inside carbon-apimgt/service-stubs location. Since those would only depend on an interface definition file, the stubs can be generated any time. But since those are referred by other modules, at build time service-stubs are built at first.
Since the service stubs only depend upon the WSDL, which already is copied to that directory, both the code for the service and the code for the handler which uses that service can reside in the same bundle, i.e - there won't be any circular dependancy.

When building the product (https://github.com/wso2/product-apim), those stubs are copied into the distribution. So at the runtime, both the code and the service-stub are present.

**Comment by giuffresoft79** [comment]
then wanting to manage the project in intellij in which command I refer to the compilation of the stub modules?

**Comment by giuffresoft79** [comment]
i see this in pom.xml file:

<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>
                                    target/generated-code/src
                                </source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by harsha89** [comment]
You can just import the carbon-apimgt project as a maven project and do the coding. :)
mvn clean install will do the build for you!

**Comment by giuffresoft79** [comment]
ok, now i see the maven-antrun-plugin in pom.xml file

**Comment by giuffresoft79** [comment]
By changing the phase in maven plugin everything compiles correctly intellij. Thanks for support

**Comment by giuffresoft79** [comment]
In carbon-multitenancy project

i would like to extend JDBCTenantManager class to persist additional fields associated with the tenant recorded in killbill but I am not clear how does instantiate when the factory method is called: TenantMgtCoreServiceComponent.getTenantManager ()

**Comment by harsha89** [comment]
Please note this is not a issue in component. Please drop  a mail to dev@wso2.org for more details
