### ISSUE TITLE
Not able to login to API mgt console

### ISSUE THREAD

**Issue by rajatsaxena6** [wso2/carbon-apimgt#4781]
**Description:**

I have installed the WSO2 api mgnt on my system.But I am not able to login to the mgnt console running on localhost:9443/carbon using the default admin/admin credentials.
Error 403 forbidden is occuring .

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abimarank** [comment]
Do you see any errors in logs?

**Comment by SwatiNEC** [comment]
Do not use JDK1.8.0_151 due to a known issue. So you can proceed with following two approaches:

1. You can downgrade from JDK1.8.0_151 to JDK1.8.0_144;
2. And if you don't want to proceed with the downgrade of JDK version,then you can disable the compression in Tomcat repository/conf/tomcat/catalina-server.xml, switching compression to "off" instead of the default which is "on".

**Comment by praminda** [comment]
@rajatsaxena6 please reopen the issue if cause of the issue is different from what @SwatiNEC has suggested
