### ISSUE TITLE
Cannot set additional parameters when generating SDKs

### ISSUE THREAD

**Issue by vlgunarathne** [wso2/carbon-apimgt#4786]
**Description:**
As of the current implementation of generating SDKs for APIs in API Manager 3.0.0, a user cannot set additional parameters to do customization when generating SDK for a particular language/framework.
Eg:
Android SDK has additional libraries such as okhttp-gson, retrofit, volley.
These can be generated using the CLI tool as follows,

mvn clean package java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l android **--library=volley** -o /var/tmp/android/volley/ 

**Suggested Labels:**
Improvement

**Suggested Assignees:**
@vlgunarathne

**Affected Product Version:**
APIM 3.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by yhilem** [comment]
Hi Viduranga,

As promised [1] I come back to have hope for some good news.

We are upgrading to APIM 2.6.0.
I hope that this feature will be integrated quickly in this version because we need it when qualifying version 2.6.0.

[1] http://wso2-oxygen-tank.10903.n7.nabble.com/APIM-Generating-SDKs-for-APIs-in-API-Manager-Store-tp152040p153527.html

Thanks,
Youcef HILEM
