### ISSUE TITLE
Application grant type tick box inactive without Callback URL

### ISSUE THREAD

**Issue by rmsamitha** [wso2/carbon-apimgt#4933]
**Description:**
In API store, in a certain application related page, by default, the 'Code' Grant type and 'Implicit' Grant type tick boxes are inactive.  We cannot select them without entering the Callback URL which is also a later (next) field in the form. So actually we cannot select the 'Code' or 'Implicit' grant type without the prior knowledge that we should have entered the Callback URL first to select that.

Making this Code/Implicit grant tick boxes innactive by default is originally intended to make the call back url a mandatory field, if the Code grant type is selected. So this conditioning should be reversed. So make this 'Code grant' or 'Implicit grant' tick boxes not innactive by default. And display a message under 'Grant Types' similar to below. 
"Callback URL is mandatory if you select 'Code' or 'Implicit' grant types"

And also make the "**Callback URL**" field label display as mandatory by suffixing an asterisk (*) to it whenever any of those 2 tick boxes are selected. i.e. **Callback URL***

And if somebody select it and then click 'Update' without filling the callback url, popup an alert box saying something as "Please enter Callback URL to update the application. It is mandatory to have callback url, if you have selected the 'Code/Implicit' grant type".

**Suggested Labels:**
APIM 2.2.0

**Affected Product Version:** 
APIM 2.1.0

**Comment by ChamNDeSilva** [comment]
Documentation is updated in previous versionseith following note.
"By default the implicit and code grant type selection checkboxes are disabled in the UI. You need to enter the callback URL first to enable selecting the code grant type."
And instructions provided to first add the callback URL before selecting the grant type.


When this git issue is fixed, please update the following docs accordingly as 2.x.x docs also have fixed with adding the aforementioned note. But after fixing this git issue, the user can first select the grant type and then add the callback URL.

**Comment by tharindu1st** [comment]
4.0.0 having new ui, hance this was invalid.
