### ISSUE TITLE
Problems with field "Visible to Roles" in API edit in Publisher

### ISSUE THREAD

**Issue by herlanijunior** [wso2/carbon-apimgt#5369]
**Description:**
The field "Visible to Roles" is not respecting the role case after saving and editing the API. Always convert to lowercase and if enter in field is necessary to fix the case to remove the error

**Suggested Labels:**
APIM 2.2.0, Severity Major

**Suggested Assignees:**
- none

**Affected Product Version:**
API Manager 2.2.0

**OS, DB, other environments details and versions:**    
CentOS 6,

**Steps to reproduce:**
Create an API that restrict access with "Access Control" with a role name that contains at least one uppercase letter. Complete the API creation. After saving and publishing the API return to overview and you will be able to check the case change. Editing the API the case will be lowered in text field

**Related Issues:**
- none

**Screenshots:**
![report-bug-s1](https://user-images.githubusercontent.com/3765140/39868047-4c8555d0-542e-11e8-807b-fcd5aea42f08.png)
![report-bug-s2](https://user-images.githubusercontent.com/3765140/39868048-4ca68c28-542e-11e8-9ef9-ec287f226652.png)
![report-bug-s3](https://user-images.githubusercontent.com/3765140/39868049-4cc67b46-542e-11e8-992d-7b0e14e367d8.png)

**Comment by praminda** [comment]
Guys,
 Looks like we make the publisher restriction roles to lowercase in  [APIProviderHostObject#L913](https://github.com/wso2/carbon-apimgt/blob/6.x/components/apimgt/org.wso2.carbon.apimgt.hostobjects/src/main/java/org/wso2/carbon/apimgt/hostobjects/APIProviderHostObject.java#L913). 
This should be the cause of the issue.

**Comment by Megala21** [comment]
We are changing it to lower case, while adding to registry because of following reason.
When registry does a solr search all the query parameters given will be converted to lower case. 

While indexing if a registy property is added with mixed case or upper case, when indexing, in registry level we do not convert it to the lower case, so the indexed data will have original format, but in registry search it will have the lower case, due to that relevant APIs will not be returned.

However this is not an issue for registry attributes, as when indexing registry attributes in indexing level, it is converted to lower case before doing indexing. That is the reason, we were able to have the API Name or other meta data in mixed case which we store as registry attibutes.

In order to fix this we need to change the indexing mechanism of properties in registry level, to follow the same that we do for attributes.
